name: Ubuntu
on:
  pull_request:
    branches: [master]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v3.2.2
        with:
          version: stable
      - run: chmod +x build.sh 
      - run: ./build.sh
      - run: nimble test